---
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: platonus
      POSTGRES_PASSWORD: platonus
      POSTGRES_DB: platonus
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U platonus -d platonus" ]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://platonus:platonus@db:5432/platonus
      SECRET_KEY: Vo4OHKokkPCLy8390OVlSYvD0tYL9yqV0uPepcLg-fQ
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
